name: Cypress UI Tests

# Avisa o GitHub para rodar isso toda vez que você der um push
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Rodar os testes do Cypress
        uses: cypress-io/github-action@v6